### ISSUE TITLE
Doxygen call graph missing

### ISSUE THREAD

**Issue by pavanakumar** [mosra/m.css#102]
I have switched to m.css for documenting my source code. I run using Doxyfile-mcss shown below (from m.css docs)

```
@INCLUDE                         = Doxyfile
GENERATE_HTML             = NO
GENERATE_XML               = YES
XML_PROGRAMLISTING = NO
```

When I run `./doxygen.py` the output it says

```
Running dot ...
```

But no call graphs are actually visible in the m.css output html (no png or svg files are created). Is dot output not supported in m.css currently? Or am I missing something? I have the `HAVE_DOT` enabled in my Doxygen to `YES` and tried both `png` and `svg` output.

**Comment by mosra** [comment]
Hi! 

Sorry to disappoint, but call graphs, ineritance graphs and other things autogenerated by Doxygen are not supported *by design* -- see the [Intentionally unsupported features](https://mcss.mosra.cz/documentation/doxygen/#intentionally-unsupported-features) list in the docs. Custom Dot graphs *are* supported, just not the autogenerated ones.

At some point in the future there might be a possibility to add such functionality with plugins, but presently not.

**Comment by pavanakumar** [comment]
If this does not support by design then I will close this issue  !

Will paste the dot files manually in important functions that require call graphs.

Many thanks for the information
