### ISSUE TITLE
Smart quotes without .. class:: reST directive

### ISSUE THREAD

**Issue by Bridouz** [mosra/m.css#11]
Hi,

I've been playing with m.css for a few days and I have a question about your smart quotes implementation.

From what I understand [here](http://mcss.mosra.cz/plugins/htmlsanity/#typography) I can have french-style quotes rendered on Pelican.

But for that I must type `.. class:: language-fr` on my reST post.

Your doc says : 

> The de­fault lan­guage is of course tak­en from the stan­dard DEFAULT_LANG op­tion, which de­faults to 'en'. 

My `DEFAULT_LANG` is `fr` so I assume that every curles would be frensh-styled. But they are not.

Am I misunderstanding the doc ?

Thanks

**Comment by mosra** [comment]
Hello again! :)

it seems that Pelican is to blame here, it doesn't properly propagate the option to the reST parser (and then I'm to blame, because I didn't test properly and claimed that something works while it doesn't). I will submit a patch to Pelican that fixes this, but it may take quite some time before it gets accepted (I'm still waiting with [a bunch more patches](https://github.com/getpelican/pelican/pulls/mosra) there).

Fortunately there's a simple workaround that will make this working for you right away: add the following to your `pelicanconf.py`:

```py
DOCUTILS_SETTINGS = {'language_code': 'fr'}
```

With this the default language for smart quotes *and also hyphenation* should be `fr`. I'll update the docs to mention this workaround (and the Pelican patch).

Pelican also offers an option to override the language per-page using the `:lang:` metadata option, but that's harder to fix, I have to think about that a bit more.

**Comment by mosra** [comment]
Pelican PR opened: https://github.com/getpelican/pelican/pull/2256

If you want, you can also get the patched Pelican along with all my other modifications from my fork:

```sh
pip install git+https://github.com/mosra/pelican.git@mosra-master
```

**Comment by mosra** [comment]
I was able to integrate the workaround to m.css itself, so now you don't even need the workaround :) Just pull the latest master with 4d4ddf0a04e2749a2e6327eb80b7d94beff4d06c included and everything should work as expected. The `:lang:` metadata option is also handled correctly now and [the docs](http://mcss.mosra.cz/plugins/htmlsanity/#typography) say that now as well.

Closing as resolved, please reopen if you encounter any problem.
