### ISSUE TITLE
Disable trailing return format

### ISSUE THREAD

**Issue by ePirat** [mosra/m.css#119]
The Doxygen documentation theme is really amazing and the search extremely useful!
I am wondering though if there is a way to disable the trailing return format or at least the auto keyword as when generating C documentation it looks quite confusing.

**Comment by mosra** [comment]
Hi, thanks for the appreciation!

This is done mainly to have the function names vertically aligned without long return type making a mess of it. But it's just a theme thing, meaning you can modify the output templates to do whatever else you prefer:

1. Copy `documentation/templates/doxygen/entry-func.html` to some otherwise empty directory and edit it to not have the trailing return (there's an `{% if %}` clause doing this, should be pretty easy to do even if you never did any HTML/Jinja coding before).
2. Run `doxygen.py` with `--template` pointing to the directory where the modified `entry-func.html` is. It will pick up this modified file and fall back to the builtin templates for other.

Providing options like this on the script side is not feasible because it would result in a ton of possible combinations and I wouldn't be able to ensure all configuration corner cases work correctly. I hope you understand :) More info: https://github.com/mosra/m.css/pull/95#issuecomment-477990330

**Comment by ePirat** [comment]
Thanks, editing the theme worked fine!
