### ISSUE TITLE
[request] Allow Newlines (\n) In DOXYGEN_M_HTML_HEADER

### ISSUE THREAD

**Issue by nephatrine** [mosra/m.css#120]
I have a very long series of <meta> and <link> elements in DOXYGEN_M_HTML_HEADER and would prefer them separated onto their own lines in the generated HTML code rather than in one extremely long line as it makes it more difficult to eyeball the code afterwards (and is not aesthetically pleasing). I tried to use \n to force them in, but I just get \n spit out into the generated HTML instead of a newline.

I realize this is a little pointless since and so would be low-priority to address (if at all), but it seems like it would be pretty easy to implement.

**Comment by mosra** [comment]
Hi, you're not forgotten -- since 1c133b1bae1b9072c4567ec2cb77202c6c2283fc there's now a possibility to supply most of the options from a python config file, which is done to alllow a lot more flexibility (among the planned features is supplying URL formatter functions, hooks for code processing etc.) *and* should also fix this issue :)

- Here's the docs explaining the new options -- https://mcss.mosra.cz/documentation/doxygen/#configuration 
- and here's how a port from the `Doxyfile` options to the `conf.py` was done in one of my projects -- https://github.com/mosra/corrade/commit/b6b431b131cb3e7a1b3be7486d87aa67c391fdd5

The original way through the Doxyfile is still supported for backwards compatibility of course, but the Python file is the preferred way going forward.
