### ISSUE TITLE
Code blocks get additional indentation in previews

### ISSUE THREAD

**Issue by TaaviE** [mosra/m.css#121]
For some reason code blocks displayed in [article previews](https://blog.aegrel.ee/tag/rawcap.html) get indented but [article itself](https://blog.aegrel.ee/reverse.html) doesn't have such an indentation. 

Is there a way to disable this behavior?

**Comment by mosra** [comment]
Hi!

Which browser? Can you post a screenshot? I don't see any difference here (on Vivaldi).

**Comment by TaaviE** [comment]
Chromium 79.0.3945.79

![Preview](https://user-images.githubusercontent.com/15741449/71734529-d8f09f00-2e54-11ea-966c-3ef76dab0f69.png)

![Article itself](https://user-images.githubusercontent.com/15741449/71734543-e0b04380-2e54-11ea-85ae-3a7c5e01c691.png)

**Comment by mosra** [comment]
Err .. sorry, spoke too soon, now I see it :) This is because the theme doesn't expect full contents of the article being shown in previews and thus causes excessive indentation in `<pre>` block.

There's two options:

- either make the previews shorter (not sure which Pelican config option is that anymore -- I'm personally always using the `:summary:` metadata -- so it looks like e.g. here: https://blog.magnum.graphics/backstage/ (the theme also makes the previews with a slightly larger text etc., with the assumption it's just a single paragraph)
- or modify the template to not indent the summaries -- unindent these lines in particular: https://github.com/mosra/m.css/blob/6eefd92c2aa3e0a257503d31b1a469867dfff8b6/pelican-theme/templates/article_header.html#L30 and https://github.com/mosra/m.css/blob/6eefd92c2aa3e0a257503d31b1a469867dfff8b6/pelican-theme/templates/archives.html#L56

**Comment by TaaviE** [comment]
Thanks for the solution, I'll probably write a few summaries.
