### ISSUE TITLE
Link lists don't get wrapped on tag pages on mobile

### ISSUE THREAD

**Issue by TaaviE** [mosra/m.css#122]
I forgot to clean up a link in one of my articles and now [one of my tag pages](https://blog.aegrel.ee/tag/git.html) has a link that doesn't get wrapped. This causes Google to label the page as mobile-unfriendly because the page gets flagged as "Clickable elements too close together", "Text too small to read" and "Content wider than screen", no other page has been flagged like that for me.

![image](https://user-images.githubusercontent.com/15741449/72227872-fc7cbd80-35a9-11ea-877a-9dd35d40dbe0.png)

**Comment by mosra** [comment]
Hi, sorry for replying four months late -- was busy on another project.

This is a good idea, actually! :100:  In 48bbdc211b65ca022306a32d234ca0b34d60f328 I added a new CSS class `.m-link-wrap` that [allows the link to break at any point](https://mcss.mosra.cz/css/typography/#text-alignment-and-wrapping), and since 8774635585cfa72987dff5470d1c179c10bf3052 the `m.htmlsanity` plugin adds that class implicitly for all links that are just URLs.

All you need to do to fix this is pulling latest master and possibly regenerate your CSS style in case you have some modifications on top :)
