### ISSUE TITLE
PyCharm components.py label_flat_danger incorrect call argument

### ISSUE THREAD

**Issue by egberts** [mosra/m.css#125]
I ran PyCharm code inspection on my entire pelican/m.css and came across some 'warnings' for m.css.

Something about the last argument (`content`) of `label_flat_danger` function being incorrect.

No further details given.   May or may not be an error.

**Comment by mosra** [comment]
No idea. All reST roles have the same signature, and the signature is based on the official docs:

https://docutils.sourceforge.io/docs/howto/rst-roles.html

That said, docutils aren't really an example of idiomatic or overwhelmingly sane Python code. But the documentation of that lib is extremely sparse and the inner magic sometimes impenetrable, so I won't attempt changing this in any way because what's there right now, works.
