### ISSUE TITLE
Need to expand environment variables while copying referenced files

### ISSUE THREAD

**Issue by thomthom** [mosra/m.css#127]
I was trying out m.css and it looks really promising. I found one issue in while testing this, we use environment variables in the Doxygen config for some of the reference files.

https://github.com/mosra/m.css/blob/6eefd92c2aa3e0a257503d31b1a469867dfff8b6/documentation/doxygen.py#L3642-L3660

I think this can be addressed by having the script expand the environment variables. I could give it a stab to create a PR if that sounds acceptable.

**Comment by mosra** [comment]
Hi, 

this should be possible since 1c133b1bae1b9072c4567ec2cb77202c6c2283fc -- there's now a possibility to supply most of the options from a python config file, which is done to alllow a lot more flexibility (among the planned features is supplying URL formatter functions, hooks for code processing etc.) and should also make your case possible -- in particular, take a "template" input Doxyfile, expand env vars in it and save it to a Doxyfile that then gets processed further. Or if you need that in the `EXTRA_FILES` / `STYLESHEETS` / `FAVICON` ... options that can be specified directly through Python, you don't even need to do any Doxyfile processing.

- Here's the docs explaining the new options -- https://mcss.mosra.cz/documentation/doxygen/#configuration
- and here's how a port from the Doxyfile options to the conf.py was done in one of my projects -- mosra/corrade@b6b431b

The original way through the Doxyfile is still supported for backwards compatibility of course, but the Python file is the preferred way going forward.

**Comment by thomthom** [comment]
That sounds great! Having the config for m.css makes sense as well. I'm in the process of converting our current docs to m.css and I have a separate Doxyfile that inherits from the main one just for that.
Having the config file in python allows for even more flexibility. 👍

**Comment by mosra** [comment]
The split is a bit weird at this point (you still need to patch the original Doxyfile to enable the XML output and disable the HTML output) so you most probably end up with three files anyway. In the future I might consider adding an ability to generate a Doxyfile from a pure-python config, but right now it's like this.

**Comment by thomthom** [comment]
That's fine, an extra file doesn't hurt. Main value is being able to use environment variable to account for local dev environment vs build machine environment.
