### ISSUE TITLE
Option to mute warnings for _EXPORT?

### ISSUE THREAD

**Issue by thomthom** [mosra/m.css#128]
https://github.com/mosra/m.css/blob/6eefd92c2aa3e0a257503d31b1a469867dfff8b6/documentation/doxygen.py#L284-L286

Would it be possible to have an option to mute this warning? It's causing too much noise in the project I'm currently working on.

Also, why is this considered "suspicious stuff"?

**Comment by mosra** [comment]
Hi and sorry for replying two months late -- was busy on another project.

At least in the project for which the doc generator was originally created, various `_EXPORT` macros expand to `__declspec(dllexport)` and it wasn't desirable to have those in the output. Since this is likely very project-specific (and each project would need different set of warnings), I'm removing this -- 05ea54c68b8891ebff6191c67095a7a44fc84763.

**Comment by thomthom** [comment]
No worries, I know what's it like to maintain open source projects - you don't have time to always be responsive.

Thank you very much for providing such a great theme!
