### ISSUE TITLE
[ImageGrid] 'PngImageFile' object has no attribute '_getexif'

### ISSUE THREAD

**Issue by Bridouz** [mosra/m.css#13]
Your ImageGrid function is really nice but it does not work with png files.

PNG files does not support exif data.

Thus what could be done with the plugin if the images are screenshots ? Screenshots do not have *exposure*, *iso* and stuffs so the plugin fails with that too.

Maybe `images.py` could include an alternative where specific exif data are not found like only displaying the filename.

**Comment by mosra** [comment]
Hi,

the image grid is unfortunately hardcoding a lot of assumptions as I originally made it just for publishing JPEGs with some EXIF information ... and then had no time to redo it in a proper way :D

I have the following ideas on my TODO list:

-   Make the EXIF extraction optional with graceful fallback -- if the file is not a JPEG, for sure it doesn't have information about shutter speed or ISO, so it doesn't make sense to try to find that information there. I don't think adding `pyexif` as another dependency would be worth it -- PNGs often don't have any metadata at all.
-   Make it possible to configure what EXIF properties are shown (someone might want to show a date instead of ISO, for example)
-   Make it possible to specify a custom title for each (instead of using the EXIF info), for example like this:

    ```reST
    .. image-grid::

        {filename}/a-picture.jpg Title for that picture
        {filename}/another.png Title for the other picture
    ```

**Comment by mosra** [comment]
With 525dedb96b43ce87e00a842c51a3b24f8877e71e the image grid no longer freaks out and dies when encountering a file without EXIF info, instead it just doesn't show any caption. 

Would that be enough for you at the moment, or do you need something more from the above list?

**Comment by Bridouz** [comment]
That's really nice, thanks.

Working like a charm

**Comment by mosra** [comment]
Great, so closing as resolved then :)
