### ISSUE TITLE
How to embed Youtube link to the doc?

### ISSUE THREAD

**Issue by tsung-wei-huang** [mosra/m.css#184]
Hi, I am trying to use the following HTML block to embed my youtube tutorial into the doxgyen page:

```
\htmlonly
< iframe width="500" height="315" src="https://url-to-embedded-video" frameborder="0" allowfullscreen>
\endhtmlonly
```

However, it doesn't seem to work under m.css generated page, and there is a warning not being able to parse `iframe`. Do you know what the best way is to add a youtube link?

Thanks

**Comment by mosra** [comment]
(Sorry for *embarrassingly* late replies, finally got a chance to get back to this project.)

The reason is that Doxygen 1.8.17 and before didn't include `@htmlonly` in the generated XML (only `@htmlinclude` worked), but that got fixed in https://github.com/doxygen/doxygen/pull/7481 which is shipped in 1.8.18+. To ensure nothing else prevents this, I added a test for embedding an `<iframe>` in fb5fd851bb0d5bd855ffeaaf560a9a8c55297d18.
