### ISSUE TITLE
Doxygen: new upstream feature adds Doxyfile.xml which breaks m.css XML consumption

### ISSUE THREAD

**Issue by marzer** [mosra/m.css#200]
As of https://github.com/doxygen/doxygen/pull/8463 Doxygen spits out an XML rendition of the doxyfile contents as `Doxyfile.xml`, which m.css dutifully tries to consume as though it were a `<compounddef>` or similar.

I guess you could just skip/delete the `Doxyfile.xml`, though a more tool-friendly way around this would be to expose an `--ignore` option to do the inverse of what `--wildcard` does now, to allow tool devs to say "hey, ignore any xml files matching this pattern", and always add `Doxyfile.xml` to it implicitly.

(it occurs to me that you may also want to use the `Doxyfile.xml` to inform m.css behaviour; it seems a pretty useful feature and probably one Doxygen should have been doing a long time ago hah)

**Comment by mosra** [comment]
(Sorry for *embarrassingly* late replies, finally got back to this project and to the final boss that is Doxygen.)

This is now fixed with a variant of #207, commited as 45911a188292a62b49ca4b226f590e9ca8cb75fa.

> it occurs to me that you may also want to use the `Doxyfile.xml` to inform m.css behaviour

Yes, in an ideal world, and if 

> probably one Doxygen should have been doing a long time ago hah

would hold true. But in reality, I have to parse Doxyfile *first* and only then execute Doxygen, because it's stupid: https://github.com/mosra/m.css/blob/013b70867ebffe7d9771e1b274aed09e01db19df/documentation/doxygen.py#L3886-L3890

Lalala :notes:

**Comment by marzer** [comment]
Thanks for addressing this :)

> Sorry for embarrassingly late replies

Man, absolutely no worries. I know the feeling. Projects don't just sneak away, they sprint away from us like they stole something.
