### ISSUE TITLE
How can I extend the navbar to show a list of  enums, structs, unions, typdefs ... ?

### ISSUE THREAD

**Issue by Marco-Israel** [mosra/m.css#204]
Hello 

How can I extend the navbar to show a list of  enums, structs, unions, typdefs , ... ?

e.g. 
https://code.gnucash.org/docs/MAINT/functions_eval.html

**Comment by mosra** [comment]
(Sorry for *embarrassingly* late replies, finally got a chance to get back to this project.)

This is one of the intentionally unsupported features, [as listed in the documentation](https://mcss.mosra.cz/documentation/doxygen/#intentionally-unsupported-features) -- I don't see any value in providing such flat lists, a file or a namespace overview page can give you the same information but without mashing all enums or typedefs from all namespaces together.

Alternatively I have a TODO item for the search functionality, where you could search just for enums/functions/... instead of any symbol, but that's not a high-priority feature at the moment.
