### ISSUE TITLE
Include functions inside file pages

### ISSUE THREAD

**Issue by Leandros** [mosra/m.css#25]
Currently, the pages for files do not include freestanding functions declared inside the functions. Only namespaces or classes are shown. 
Vanilla doxygen does, though. The XML does not list functions inside the files .xml, only namespaces. Though, by looking up the namespace one can get the functions, since they contain where they're declared.

*Edit:* This only seems to be the case, when they're not in the global namespace.

**Comment by mosra** [comment]
Hi! I have a patch for this lying around, just need to submit it to Doxygen. I am also missing this functionality, turns out it's just a single `if` that disables this for XML output to "avoid duplicates".

Then I need to properly handle the duplicates, though :)

**Comment by Leandros** [comment]
https://github.com/doxygen/doxygen/blob/d4beb392b452d14d375e1406ec4fb0f6436081ee/src/xmlgen.cpp#L1035 ? ;)

**Comment by mosra** [comment]
Yup. And second time a few lines below.

Afaik the HTML output redirects the detailed docs link to namespace doc page, so then I need to do the same here.

**Comment by Leandros** [comment]
Yes, that is correct.

**Comment by mosra** [comment]
The Doxygen part of this feature is submitted in https://github.com/doxygen/doxygen/pull/653, I'm working on the m.css part now. It kinda blew up (as usual :D), so it might take some time until it's ready.

**Comment by mosra** [comment]
The m.css part is implemented in 5ab694a34d653a0cd4b89782f73ac17ce502568c, feedback welcome :) 

Unfortunately while testing I uncovered two really annoying Doxygen bugs that need to be fixed:

- Typedef types, detailed docs etc. have broken namespace-relative links when appearing in a file-level documentation. This is kinda hard to fix, I presume.
- The XML output provides no information about enclosing namespace of the symbols, so the file-level documentation lists everything as `foo()` instead of `Namespace::foo()`. This might be rather easy, as enclosing namespace is already provided correctly for inner classes and namespaces.

I'll tackle these two some time later (keeping them [here](https://github.com/mosra/m.css/projects/5) for reference), I need a break from digging through Doxygen sources now :/ (Help in this area very welcome ;))

**Comment by mosra** [comment]
Just FYI, https://github.com/doxygen/doxygen/pull/653 was merged and released in 1.8.15, however with a different option name: `XML_NS_MEMB_FILE_SCOPE` instead of `XML_NAMESPACE_MEMBERS_IN_FILE_SCOPE`. The theme is adapted to that in 1a07c2e08960af3b784a5922633405076a9a2864 and the online docs are updated now as well.
