### ISSUE TITLE
Request: Publish to PyPI

### ISSUE THREAD

**Issue by parker-research** [mosra/m.css#253]
This project is awesome! It would be great if you could publish it to PyPI so it can be install normally, and the `doxygen.py` and `python.py` scripts can be called in the way that Python projects are normally run.

If you're interested in this, let me know and I may be able to help package it up quickly.

It would also be great to tag releases on GitHub with version numbers as this project moves forward.

**Comment by mosra** [comment]
Hi, thanks for your interest in this library.

I'll try to go over your other suggestions and PRs as soon as I'm able to, but just so you know I'm in a perpetual state of not enough free time, so it might take a while. 

Which is unfortuantely also an answer to your request -- publishing to PyPI would mean extra effort (how do I even make a pip package depend on system-installed doxygen? etc), publishing in a nice way would mean making versioned releases, and making nice versioned releases would at the very least mean writing proper changelogs, ideally also having some place to put release notes to and such. My main project is [Magnum](https://github.com/mosra/magnum), and even there I'm *struggling* to make regular versioned releases. In comparison, m.css is just a supporting project, and for my own sanity I'm trying to keep it as effortless to maintain as possible. Sorry.

This *might* change in the future, but for now I don't want to do any packaging, versioning or anything else that goes beyond making sure it works. Downstream projects such as [Poxy](https://github.com/marzer/poxy) have versioned releases, but their scope and target audience is also a bit different.

**Comment by parker-research** [comment]
Can I request that you leave this issue open, and instead simple let it linger until later to centralize discussion over the matter?

**Comment by parker-research** [comment]
Would you be willing to accept just a `pyproject.toml` so that it's all in a single package? You don't have to version or publish it.

Benefits: It'd allow you to get rid of the `sys.path.insert` hacks, which will allow static type checkers to do their job properly.

**Comment by parker-research** [comment]
I disagree; there are lots of libraries out there that require extra installs. Pillow, GDAL, most machine learning computation libraries, anything that involves graphics cards, etc.

Worst case - you keep the issue open, and one day someone solves it.

I'd be happy to add the doxygen CMake build (and maybe even latex deps too) to the pyproject.toml, if that's the hold-up.

Don't let perfect be the enemy of better.

**Comment by mosra** [comment]
No, no, no, no. I don't want to maintain any of that, and especially not a fractal of CMake buildsystems ran from within a python package install. Because, as I unfortunately learned, as soon as I add any feature anywhere, people start using it, and demand more. So I have to make sure that I only add features that I don't see becoming a maintenance nightmare for years forward. Even just _running_ Doxygen is a maintenance nightmare already.

If you _need_ the project to be installable for whatever reason, maintain a downstream fork. Poxy, mentioned above, started like that, and the collab is just fine -- I happily upstream features that make sense in context of the bag of loose scripts that's m.css, and Poxy then deals with additional magic, packaging, styling, whatever, that makes sense for them.

**Comment by parker-research** [comment]
That sucks.
