### ISSUE TITLE
Request: Use a linter/autoformatter on the repo

### ISSUE THREAD

**Issue by parker-research** [mosra/m.css#254]
Have you considered using a linter/autoformatter like Ruff on this repo's Python code? There's quite a few aspects that would be easier to maintain if it used these standard dev tools. 

Type checking would be a bonus! Pyright catches several type checking errors in the Python code right now; would be good to enforce those a bit better in the CI pipeline.

**Comment by mosra** [comment]
No, sorry, definitely not :sweat_smile: 

My experience with linters and formatters on other projects was that more often than not they worked _against_ me, forcing me to spend extra time adding suppressions or researching formatter options to have it closer to how I want the code to look. And then regularly running into issues where the formatter version on the CI and the version used locally disagreed about how the code should look, or the formatter making a mess in diffs, stomping on changes when rebasing, and just generally causing more pain than good.

Compared to e.g. [Magnum](https://github.com/mosra/magnum), the project is not _that_ big for this to be a maintenance problem. I am balancing this by making sure ~everything is covered by tests.

The type annotations may likely be wrong in some places. I use them mostly as a means of self-documenting code, and only in places where the types are actually complex. Possibly related is that a lot of the doxygen/python processing code uses `SimpleNamespace`, which felt like a good idea at first, but eventually proved to be an annoyance because it's impossible to know what all fields given instance has or should have. That's the important part that should get fixed, yet it's something where a type checker would think it's completely fine. Which pretty much sums it up I think.
