### ISSUE TITLE
For file level attributes, create the header with the attribute name

### ISSUE THREAD

**Issue by Leandros** [mosra/m.css#26]
If I annotate a file, with something like:

```
/*!
 * \file bar.hpp
 * \copyright 2018 Foo Bar.
 * \author Bar Baz
 */
```

the original doxygen doc would generate something along the lines of:

> **bar.hpp**
>    **Copyright**
>         2018 Foo Bar
>     **Author**
>         Bar Baz

while the current m.css, simply dumps the texts, without the headers. Wouldn't it be useful, if the headers would be retained equally?

**Comment by mosra** [comment]
Sure! I am not using the `@copyright`, `@author` commands myself, so this case probably got omitted.

I'm not able to get to my computer until Friday or so, is it okay if this won't be fixed immediately? :)

**Comment by Leandros** [comment]
No hurry. ;)
Just noticed the same for `@since` on functions, classes or defines. Would be useful to be annotated as well, it just appears as a normal remark.

**Comment by mosra** [comment]
Yup, I'll go through all the missing section commands when I get to it.

**Comment by mosra** [comment]
With 0bca7d74c00244c3a8aa67ca214e35188f7be30f, the following sectioning commands are now supported:

- `@author`, `@authors`, `@copyright`
- `@version`, `@since`
- `@date`
- `@pre`, `@post`, `@invariant`
- `@par` and RCS entries (`$Id: something $`)

The `@par` command is now also able to append to previous sections of any kind if its title is omitted, mimicking what the stock HTML output is doing. 

I kinda hate how the output currently wasted space (wasn't any better with stock doxygen), will improve it once I figure out the best way to do that. Maybe it ends up to be in some sort of table similarly to how `@param`, `@return` etc. for functions is handled at the moment.

Please reopen and/or complain if something is not as it should be :)
