### ISSUE TITLE
dox2html5.py generates empty webpage

### ISSUE THREAD

**Issue by bjfar** [mosra/m.css#36]
I am following the guide at http://mcss.mosra.cz/doxygen/#basic-usage, and there don't seem to be many steps to it, however I only get an empty website produced at the end when I run this on my code base. Running normal doxygen works fine, however there is no visible results of any code being parsed when using dox2html5.py.

Do you have any tips on debugging this situation? I attached the stdout I get from running the script; there are loads of warnings and so on, and I'm sure lots of parsing issues in amongst the code since the doxygen generation is poorly tested, however I am still surprised to get nothing at all generated. I have attached screenshots showing the difference between native doxygen html and dox2html5.py output.

Edit: In case you are interested in testing it yourself, the code can be downloaded from https://github.com/bjfar/gambit_1.1.git (on the branch docs_pelican), and I simply ran the command from inside the 'doc' directory as:

`<path_to_repo>/m.css/doxygen/dox2html5.py --debug Doxyfile-mcss
`

with doxygen html generated for comparison with

`doxygen doxygen.conf
`

Edit 2: Ahh, perhaps my doxygen version is too old, I missed your giant notice about that. I am on version 1.8.11-1, will upgrade and try again.

Edit 3: No dice, upgraded to doxygen 1.8.15, same outcome.

[tmp_output.txt](https://github.com/mosra/m.css/files/1943148/tmp_output.txt)
![doxygen](https://user-images.githubusercontent.com/2520133/39193810-3f131790-47d4-11e8-837d-0a421705aa21.png)
![dox2html5](https://user-images.githubusercontent.com/2520133/39193818-42039fa6-47d4-11e8-8a61-9fe66df59c0a.png)

**Comment by mosra** [comment]
Hi! :)

Wow, a very detailed report. Great job!

This is related to the following [feature](http://mcss.mosra.cz/doxygen/#important-differences-to-stock-html-output):

> - Files, di­rec­to­ries and sym­bols that don’t have any doc­u­men­ta­tion are not present in the out­put at all. 

In particular, when your files are in a directory / namespace that's not documented, it will cause them to not appear in the file / symbol tree at all. I just expanded the documentation with a [Troubleshooting section](http://mcss.mosra.cz/doxygen/#generated-output-is-mostly-empty) that explains how to solve this.

Let me know if this fixes it for you.

**Comment by bjfar** [comment]
Ahh ok, so I just have to go make sure all the "layers" leading up to my documented code are also documented? Alright, I'll go check that out, thanks!

**Comment by mosra** [comment]
Hmm. I see it like this:

I would make Doxygen read files from the `gambit_1.1/Utils/include` and `gambit_1.1/Core/include` directories, so the path Doxygen sees is equivalent to the path you use for `#include`. So, something like this in `Doxyfile`:

```ini
INPUT = gambit_1.1/Utils/include \
        gambit_1.1/Core/include
```

That way the generated documentation will also have the titles equivalent to the include path, like I have here for example, corresponding to `#include <Magnum/Math/DualQuaternion.h>`:

![image](https://user-images.githubusercontent.com/344828/39238671-203abf66-487f-11e8-9412-d02d5b98ed7a.png)

Which then means, in order to succeed, you just have to document the `gambit/` and `gambit/Utils/` or `gambit/Core/` directories. That's not too much in my opinion. As to where to add that documentation -- no, it would be stupid to copy that in every file :) For example, in Magnum I have a dedicated [doc/namespaces.dox](https://github.com/mosra/magnum/blob/master/doc/namespaces.dox) file that contains documentation for dirs and namespaces and is an additional location referenced from INPUT in the Doxyfile. Look there for inspiration, the important pieces are the `@dir` and `@namespace` keywords.

**Comment by bjfar** [comment]
Hmm ok, I started doing something like that but it seems to not work still. I'll try restructuring the input command like you suggest.

**Comment by mosra** [comment]
Oh, also, there is the `STRIP_FROM_PATH` option with which you could use (or maybe that one will work better). Leave INPUT as you have it, but add the above two to `STRIP_FROM_PATH` instead. Then again you need just to document the paths that are not stripped.

[Magnum's Doxyfile](https://github.com/mosra/magnum/blob/master/Doxyfile) for reference.

**Comment by bjfar** [comment]
Hmm ok I tried doing this in the doxyfile:
```
INPUT                  = ../ColliderBit \
                         ../Core \
                         ../DarkBit \
                         ../DecayBit \
                         ../Elements \
                         ../Logs \
                         ../Models \
                         ../PrecisionBit \
                         ../Printers \
                         ../ScannerBit \
                         ../SpecBit \
                         ../Utils \
                         ../FlavBit

FULL_PATH_NAMES        = YES
STRIP_FROM_PATH        = ../ ../Utils/include
```

And added files containing descriptions for each folder under "Utils". So now I get a smaller tree, plus descriptions, when running under plain doxygen, but I still get nothing with mcss. These are the two results of the "files" page:

![doxygen2](https://user-images.githubusercontent.com/2520133/39240516-e376cfb4-487b-11e8-8c2b-7b610d64d74b.png)

![mcss2](https://user-images.githubusercontent.com/2520133/39240523-e7bfe434-487b-11e8-9323-c9a0bd71ce36.png)

**Comment by mosra** [comment]
Huh.

Can you push your latest changes and the Doxyfile to the repo? I'll look at it locally.

**Comment by bjfar** [comment]
Ah sure, thanks, done. Sorry if it is something dumb, we don't really know doxygen well, we've only been using it in a stupid way so far. The doxygen.conf file is in "gambit_1.1/docs", I have been running both doxygen and your script from that directory.

**Comment by mosra** [comment]
Okay, haha, this blew up a bit :D 

Right after cloning, running the script gave me the `gambit` and `Utils` directories in the file list, not sure what was the problem, maybe Doxygen behaves slightly differently based on where in the filesystem is the project cloned (oh well). After that I discovered that `CREATE_SUBDIRS` is enabled. That basically scatters the XML files across seven bazillion subdirectories (to work around limitations of ancient filesystems) and m.css doesn't support that (and probably never will be, too much effort for too little gain). It used to generate a mostly empty output which is useless, in e93df33fabf9ee5d627eaf1d6e0256bac33ffcdc I made it simply abort. 

So I disabled `CREATE_SUBDIRS` in my working copy and right after that came across a few very ugly very interesting Doxygen featurebugs related to `JAVADOC_AUTOBRIEF`, which caused assertions in a few places. See 406ecd7427081b62dc6787f2611eeee48ca4f500 for details, I tried to extract as much info out of those bug-ridden outputs as possible, but it's not really much. I'm thinking you would be better off by just disabling it completely and using explicit `@brief` instead or at least get rid of the `****` and `====` lines in the doc blocks which are making Doxygen *really* confused.

The output looks like this for me now and nothing is asserting with `master` anymore:

![image](https://user-images.githubusercontent.com/344828/39246573-4131d7f0-4897-11e8-876e-67c40ba342a0.png)

The namespace and class lists are filled now as well, though the files don't list any members .. probably because the classes have neither brief nor detailed docs, but you know that already ;) Also the `///` copyright / author blocks at the beginning of each file are cluttering the output quite a bit, you might want to make them just `//` to hide them from Doxygen.

I need to take a shower now after seeing all those fresh Doxygen bugs :shower: :smiley:

**Comment by mosra** [comment]
Great. So I guess I can close this one, then? :)

**Comment by bjfar** [comment]
Hmm well I still get no files listed, however after turning off CREATE_SUBDIRS and JAVADOC_AUTOBRIEF I do now get classes and namespaces listed. So that's great! Not sure what's up with the files though.

**Comment by mosra** [comment]
As far as I could see, JAVADOC_AUTOBRIEF only caused some crashes, which I fixed, so that should be unrelated. Command line I used here, just for the record:

```sh
cd ~/Code/m.css/doxygen
./dox2html5.py ~/Code/gambit_1.1/doc/Doxyfile-mcss --debug
```

What does it print in the last few lines of output if you run it like this?

```sh
./dox2html5.py ~/Code/gambit_1.1/doc/Doxyfile-mcss --debug --wildcard "dir_df9a1ca30d1b651f859d428388d23aec.xml"
```

(this file, at least in my case, is the root `gambit` directory).

**Comment by bjfar** [comment]
Hmm well actually it suddenly worked. I now get the output you showed, so I guess it works. I think I deleted the doxygen_out directory that time. Possibly the script doesn't regenerate everything if there is existing output?

**Comment by mosra** [comment]
Riight, that makes sense. The most probable cause is that there were some stale XML files from the previous runs (when you had different `INPUT` and/or `STRIP_FROM_PATH`) and those messed up the tree building (referencing files / directories that were no longer there etc.). The script can't really do much about that.

**Comment by bjfar** [comment]
Cool, well thanks for all the help, looks like I am in business now! I'll close this for you :).
