### ISSUE TITLE
Conflicting styling/layout opening index.html inside a frame

### ISSUE THREAD

**Issue by bjfar** [mosra/m.css#40]
Let me apologies in advance for what is going to be a hopelessly vague report. I am just hoping you might give me a couple of pointers to understand how I should fix this.

I have generated some basic docs for our code, and uploaded them to the server that hosts our main website, however I get some bizarre conflicts between the styling imposed by the main site and the doxygen-generated html. See here:

https://gambit.hepforge.org/doxygen/doc_howto.html

That page actually looks pretty nice, however the top nav bar and footer are screwed up for some reason. The code doc pages are much more screwed up though, e.g.

https://gambit.hepforge.org/doxygen/files.html

where the files list opens underneath the main nav bar rather than in the "normal" content window.

I realise that it is probably hard to diagnose without knowing what our main website is doing, but I am hoping that you might have a decent guess at what should look for to try and fix theses issues.

The previous raw doxygen output didn't have any such weirdnesses. It just opened in its own little area seemingly independently of the styling of the rest of the page, so I guess there is some important difference between how the old doxygen html works vs how your fancier-styled output works. 

We are a bunch of scientists btw, understanding html and css is not our forte, so sorry for the dumb questions about web design :).

**Comment by mosra** [comment]
Hmm. I'm afraid this won't work well.

The "stock" Doxygen HTML output is just a big table layout that doesn't care much about the area it is placed in. That allows you to embed it basically anywhere, but on the other hand it isn't responsive -- it simply doesn't work well on narrow screens (or with wide content inside). 

With m.css I took the other approach -- the style expects that the content is placed right inside `<body>` and rearranges the layout based on screen width, so it is readable on both mobile phones and huge screens.

Question is: do you *need* it to be embedded in your website layout? I'm not sure that is possible without rewriting a huge portion of the CSS style, losing the responsiveness on the way. **However**, I think it could work the other way around -- embedding your left menu in the Doxygen template, for example, but retaining the top bar from m.css. Would that be okay(-ish)? 

I assume you're patching the builtin theme already to achieve the current state, so here's what you could do (disclaimer: I'm *also* not a web designer, I just ended up here because that was the sanest option -- I'll try to describe it as best as I can):

The core [grid framework is described in detail here](http://mcss.mosra.cz/css/grid/), basically it divides the screen to 12 columns that you can fill with your content, plus an ability to specify the layout differently for different screen sizes. The m.css doxygen theme uses the center 10 columns on large screens, with one column space on left and right. Since it's responsive, it can live also in just 8 or 7 columns, giving you enough space for the left menu. The relevant portion in [templates/base.html](https://github.com/mosra/m.css/blob/cb0c6101be6008a7eae7292c54f9fcbc5f15b243/doxygen/templates/base.html#L83-L93) looks like this:

```html
  <div class="m-container m-container-inflatable">
    <div class="m-row">
      <div class="m-col-l-10 m-push-l-1">
        {% if M_PAGE_HEADER %}
        {{ M_PAGE_HEADER|replace('{filename}', FILENAME) }}
        {% endif %}
{% block main %}
{% endblock %}
      </div>
    </div>
  </div>
```

and you could modify it for example like this to add the menu to the left 3 columns (add more `m-col-*` properties there to configure how it should look on smaller screen sizes, see the docs linked above).

```html
  <div class="m-container m-container-inflatable">
    <div class="m-row">
      <div class="m-col-l-3">
        <!-- your left menu code here -->
      </div>
      <div class="m-col-l-7">
        {% if M_PAGE_HEADER %}
        {{ M_PAGE_HEADER|replace('{filename}', FILENAME) }}
        {% endif %}
{% block main %}
{% endblock %}
      </div>
    </div>
  </div>
```

You could similarly "patch in" the top menu, or move that to the footer.

An alternative option to this could be keeping the m.css template as-is and just adding a bunch of menu items to the top navbar so people could go back from the documentation to your main site.

Hope this helps :)

**Comment by bjfar** [comment]
Hmm, thanks for the advice, I'll see what I can work out. Embedding our navbar in the doxygen code would be perfectly fine. Actually, I may not even bother with that; I actually did nothing at all to make it work the way it currently does, there is just some voodoo going on behind the scenes of our current setup that opens new pages in that space. I don't know how it works, I'll probably have to investigate it from that side.

I would have just made it open in a new page without the framing and navbar, but I haven't yet figured out how to do that :). But it sounds like figuring that out will be easier than fixing up the styling on the m.css side so I'll focus on that.

**Comment by mosra** [comment]
Huh, okay, I thought this was all manual work since I saw the `<link>` elements extracted and placed in `<head>` etc. Voodoo. :D

> But it sounds like figuring that out will be easier than fixing up the styling on the m.css side so I'll focus on that.

That would be my recommendation as well :)

**Comment by mosra** [comment]
@bjfar can I close this as resolved?

**Comment by mosra** [comment]
Closing as resolved.
