### ISSUE TITLE
Doxygen: search datasbase fails to load on Chrome and Edge when M_SEARCH_DOWNLOAD_BINARY = YES

### ISSUE THREAD

**Issue by marzer** [mosra/m.css#65]
See title.

Background: For ages the one guy at our office who doesn't use Firefox was having issues with the search feature and we just assumed it was something to do with an addon he had installed in Chrome. After digging a little deeper on my own machine I've been able to confirm that he's not crazy after all. We're running Windows 10, though I have no way to test how relevant that is.

Steps to reproduce:
1. Build the search database in binary mode using `M_SEARCH_DOWNLOAD_BINARY = YES`
2. Open any m.css doxygen page in Chrome or Edge
3. Invoke the search bar
4. see this forever:
![image](https://user-images.githubusercontent.com/3958019/45759463-a6576e80-bc30-11e8-88d4-4a1745d67b29.png)

Here's the offending binary:
[searchdata.zip](https://github.com/mosra/m.css/files/2397440/searchdata.zip)

Edge's dev console says this a whole bunch:
`SCRIPT5604: SCRIPT5604: buffer is not an ArrayBuffer       search.js (40,9)`

**Comment by marzer** [comment]
Annnnd now that I've gone to the trouble, I've just seen a note in your documentation about it not working on Chrome. Gah. Guess it's a known limitation after all :P

**Comment by mosra** [comment]
Yes, exactly. That's unfortunately a feature of Chrome (and Edge), as [explained in the docs](http://mcss.mosra.cz/doxygen/#search-options) -- it doesn't allow `XMLHttpRequest` on local files. You have these options:

- Keep `M_SEARCH_DOWNLOAD_BINARY` enabled and have the documentation hosted on some intranet server. That'll make it work.
- Disable `M_SEARCH_DOWNLOAD_BINARY` -- since you are serving locally, the extra download size is not much of a problem. This is *exactly* the reason why this option exists ;)

**Comment by marzer** [comment]
Yeah, using the non-binary version is totally fine. That'll teach me to RTFM, hah.
