### ISSUE TITLE
Doxygen theme: where is `latex2svgextra`?

### ISSUE THREAD

**Issue by adamnovak** [mosra/m.css#68]
I'm trying to use the Doxygen template that comes with m.css in another project; I've forked it out into https://github.com/adamnovak/mcss-doxygen-theme so I can clone it by itself in the other project's build process.

I'm trying to collect the dependencies together; apparently https://github.com/tuxu/latex2svg (which just ships a `latex2svg.py`) is one, but it looks like I also need a `latex2svgextra` module, and I can't find anything on the Internet about it besides the imports in this project.

Where is `latex2svgextra`? How does one install it?

**Comment by mosra** [comment]
Hi!

Um, I'm not sure if everything will work correctly this way, do you *really* need to do this? From a quick look I see you're also missing all the CSS files, for example. A lot of code is shared between the `doxygen/` directory and the `pelican-plugins/` directory -- and that's also where you can find both `latex2svg.py` and `latex2svgextra.py`. 

Later I'm planning to share even more code -- for example bringing [hyphenation and advanced typography](http://mcss.mosra.cz/plugins/htmlsanity/#typography) to Doxygen as well (#49), or supporting GraphViz diagrams that are now [implemented for Pelican](http://mcss.mosra.cz/plugins/plots-and-graphs/#graphs) but not yet exposed to Doxygen.

Right now, the only thing completely unrelated to Doxygen in this repo is the Pelican theme, which is just a bunch of files, everything else is used by it in some way. If you are concerned about download sizes, the files in `test/` are by far the hugest portion of the repo (> 80% of this repo size), so maybe just remove these instead. Initially I was also thinking about separating the CSS, Pelican and Doxygen portions a bit, but came to a conclusion that it would become a tangled mess of Git submodules with no real benefit, only confusing users.

In any case, I think you'll later run into needless problems when integrating upstream changes due to files being shuffled around so I don't recommend doing this ;) One long-term goal for this project is to make a package available through `pip`, so you could simply install the whole thing without the unrelated test files and site sources -- but not there yet, there are other things that have much higher priority at the moment.

**Comment by adamnovak** [comment]
Oh, if the whole repo is needed for the doxygen/ subdirectory to work,
I can just use that. I was only pulling it out because I thought it
would work on its own. I read in the documentation:

"Ev­ery­thing you need apart from Doxy­gen it­self is a Python script
and a bunch of tem­plate files. You can get that by cloning the m.css
GitHub re­pos­i­to­ry and look­ing in­to the doxygen/ di­rec­to­ry:"

To me that mean that only the doxygen/ directory was important. But I
must not have been reading things carefully, because clearly the
script goes up into the main repo:

https://github.com/mosra/m.css/blob/d58881f84b7a10a106259d9fe897b0092f94ee13/doxygen/dox2html5.py#L52

And latex2svg.py and latex2svgextra.py are right here:
https://github.com/mosra/m.css/tree/master/pelican-plugins

**Comment by mosra** [comment]
> Ev­ery­thing you need apart from Doxy­gen it­self is a Python script
and a bunch of tem­plate files.

Haha, oh well, this paragraph is a forgotten relict of the old times. Was a case in the very beginning, but not anymore. Sorry about the false impression.
