### ISSUE TITLE
Sphinx Theme support

### ISSUE THREAD

**Issue by Serkan-devel** [mosra/m.css#78]
`Sphinx` is a documentation engine, similar to doxygen. Many python projects have it alongside their project installed. Docs written in sphinx can be hosted on readthedocs.org

**Comment by mosra** [comment]
Not sure what you mean here, exactly. I guess it's not about functionality similar to the [Breathe project](https://breathe.readthedocs.io/), making the Doxygen C++ documentation readable by Sphinx, but rather providing a theme for the generated Sphinx docs, right? But a custom theme is, as far as I'm aware, not possible to be hosted on readthedocs.org anyway, you are forced to use their theme.

Theming Sphinx is, I'm afraid, completely orthogonal to m.css, since it would be just about taking the colors and fonts and reusing their original markup. And that would lose basically all the advantages and potential of m.css, like lean and efficient markup, small download sizes or fast math rendering.

On the other hand, lately I've been thinking about [writing a Doxygen replacement](https://twitter.com/czmosra/status/1079062169906499584) for C++ docs, based on reST markup (and thus aiming to be compatible with Sphinx). Together with #76 this could lead to a more flexible implementation, allowing it to be extended for documenting Python projects as well, for example.

**Comment by mosra** [comment]
Um, that didn't really help me understand what is your feature request :sweat_smile: 

- is it just about theming sphinx with the m.css (dark) theme?
- or is it about providing some Sphinx compatibility (handled by Breathe already)?
- or is it about taking Sphinx-compatible input and creating m.css-themed docs out of that?

**Comment by mosra** [comment]
Ah, I see, thanks for the link. Looks like it could be possible to base the whole theme on the m.css grid framework. I'm not sure about the search, since I would need offline access to the raw symbols to generate the search data used at runtime.

Sorry to say this, but right now this is absolutely not fitting the current roadmap, as I don't have any personal need for such functionality -- I already have a theme built and as I mentioned above, I will be going rather the other way -- implementing other backends next to Doxygen for the current theme instead of reworking current theme from scratch to work with existing third party backends (which would most probably involve reinventing the already-done things like math rendering, code highlighting and search).

Keeping this open and putting a <kbd>help wanted</kbd> label here -- if you (or anybody else) are willing to pick it up, have fun! :)

**Comment by Serkan-devel** [comment]
Would you mind if the sphinx theme is based on  [alabaster](https://github.com/bitprophet/alabaster) at first?

**Comment by mosra** [comment]
As I said -- if you want to want to have just the look&feel of m.css on Sphinx, feel free to adapt it yourself. I'm afraid I don't have the time to look into that in the foreseeable future, sorry.

**Comment by nikhilkalige** [comment]
@mosra I have been trying to find ways of generating documentation for our huge (5000 C++ files) codebase which has C++ and Python.  I have been trying to utilize breathe but it take a few hours at minimum to finish rendering. I also ran m.css and was done in a few minutes. I would be interested to see if this could be used to generate `.rst` files instead. I see that you have mentioned that you are working in this direction. I could contribute towards that effort if it is helpful. Thank you

**Comment by nikhilkalige** [comment]
I am thinking of converting the templates from html to rst, in the mean time and see the performance.

**Comment by Serkan-devel** [comment]
@nikhilkalige using sphinx?

**Comment by mosra** [comment]
@nikhilkalige After seeing what pain Breathe has to go through in order to generate `.rst` files from Doxygen markup, I definitely *do not want* to go the same direction -- too many things to break on the way (and the Doxygen markup is very limited to begin with). Instead, I wanted to have reST markup embedded directly in the code -- basically what you write with Doxygen style now, you'd be writing in reST. (Details in [the tweet](https://twitter.com/czmosra/status/1079062169906499584) I linked above.)

Once this is done, generating `.rst` files edible by Sphinx should be no problem. But again, I personally see no reason why you'd want to do that, (in my personal opinion) it's inferior in about every way -- poor search capabilities, theme producing extremely long hard-to-navigate pages by default and C++ support not really good either.

**Comment by nikhilkalige** [comment]
@mosra I really like what you have done with your theme, our code base is a mixture of Python libraries and C++ ones, I would really like them to be showcased on the same website. I was hoping to use sphinx as the tool with breathe or something similar to accomplish this.

I did look at the tweet, but I wasn't sure if you had started working on it, I would really like to help out if you would like some help.

@Serkan-devel  Yes...

**Comment by mosra** [comment]
Haha, actually I'll need Python support in the theme quite soon (doing Python bindings for [Magnum](https://magnum.graphics)), so you may get it here as well :) Subscribe to #80 for updates.

I didn't start working on the Doxygen rewrite yet, as I'm already overbooked with too many projects and too little time, and what I created here is currently "good enough" -- not perfect, but does the job. I might be revisiting the project later this year (even got an organization willing to fund me already) but ... I would need to ~~clone~~ fork myself to be able to work on all the things I want.

**Comment by mosra** [comment]
Python documentation support is now done (see #80) and I'm not planning to provide anything for Sphinx apart from what the [m.sphinx](https://mcss.mosra.cz/plugins/sphinx/) plugin does (and will do in the future) for Sphinx markup compatibility and project cross-linking.

If someone wants to take the CSS from m.css and whip up a Sphinx theme, feel free. But I don't have the resources to create or maintain it, as my focus goes into a Sphinx *alternative*, not a theme.
