### ISSUE TITLE
Triggered assertions in parse_desc_internal

### ISSUE THREAD

**Issue by Naios** [mosra/m.css#81]
Hey @mosra,

My environment is the following:
m.css: 9c97cf838ed
Doxygen: 1.8.14
Python: 3.6.1

I'm encountering two triggered assertions in parse_desc_internal when generating the documentation for Naios/continuable@20e8c7d :

```diff
diff --git a/m.css/doxygen/dox2html5.py b/m.css/doxygen/dox2html5.py
index 76857aa..3392789 100644
--- a/m.css/doxygen/dox2html5.py
+++ b/m.css/doxygen/dox2html5.py
@@ -1567,10 +1567,10 @@ def parse_desc_internal(state: State, element: ET.Element, immediate_parent: ET.
 
         # Sane behavior otherwise
         else:
-            assert not has_block_elements and paragraph_count <= 1
+            # this-> assert not has_block_elements and paragraph_count <= 1
 
             if paragraph_count == 1:
-                assert out.parsed.startswith('<p>') and out.parsed.endswith('</p>')
+                # this-> assert out.parsed.startswith('<p>') and out.parsed.endswith('</p>')
                 out.parsed = out.parsed[3:-4]
 
     # Strip superfluous <p> for simple elments (list items, parameter and
```

beside of design changes my m.css matches the one as of 9c97cf838ed .
I could also open a seperate issue for each assertion if wished.

Thanks in advance.

**Comment by mosra** [comment]
Hi, thanks for the detailed report!

I can have a look later today and try to generate the project, however if you could run the script with `--debug` and upload here the Doxygen-generated XML file it fails on (the filename will get mentioned right above the stack trace), that could speed it up a bit ;)

This particular portion of the code is often hitting very nasty Doxygen featurebugs (as the `# Sane behavior otherwise` comment may suggest). I wonder what is it this time :sweat_smile:

**Comment by mosra** [comment]
Oh, just realized: 1.8.15 fixed some of the stuff related to this (and based on that I made some changes in this function). Is there a chance you could test with 1.8.15, maybe it goes away?

Nevertheless, I want to stay compatible with 1:8.14, so this has to be fixed.

**Comment by Naios** [comment]
Thanks for your quick response, I'll try out 1.8.15 but I would prefer staying at 1.8.14 since 1.8.15 introduced some regressions (I can't remind which bugs it introduced but it prevented me from generating a project I was working on last year).

See the log and xml output attached as requested:
[xml_and_log.zip](https://github.com/mosra/m.css/files/2730465/xml_and_log.zip)

**Comment by mosra** [comment]
Thanks! Yeah, I got also quite some regressions, had to submit a few PRs for them. Is there a chance any of (https://github.com/doxygen/doxygen/issues/6715, https://github.com/doxygen/doxygen/pull/6714) affect you too? 

By the way, looking at https://naios.github.io/continuable/ I see that `search.js` is not getting downloaded, even though [I can see it](https://github.com/Naios/continuable/blob/gh-pages/searchdata.js) in the `gh-pages` branch. Maybe GitHub doesn't like the Base85-encoded file `¯\_(ツ)_/¯`. Can you try enabling [M_SEARCH_DOWNLOAD_BINARY](https://mcss.mosra.cz/doxygen/#search-options) and uploading a binary file instead? It'll be also smaller, the text version is just to work around XHR restrictions when viewing docs locally.

**Comment by mosra** [comment]
Okay, looking at this, it boils down to *a bit too much* of the documentation recognized by doxygen as brief docs, causing problems visible for example here: https://naios.github.io/continuable/modules.html

As a ~~workaround~~ fix, can you add an empty line before [this line here](https://github.com/Naios/continuable/blob/20e8c7d3e35bec9d11f5ce439c4d9897736d2028/include/continuable/continuable-primitives.hpp#L41)? That should make it put the rest into detailed docs and behave correctly.

I still need to fix the script so it doesn't blow up this way, however this is quite a pathological case that's hard to recover from. So I guess it'll just emit a loud warning (suggesting what you need to do) and ignore the whole docs.

**Comment by Naios** [comment]
So,1.8.15 triggers the assertions as well but the .html is generated instead on 1.8.14 which doesn't produce any output, although I also added the newline, thanks for the hint.
However the the output is unusable but it seems that the generation went one step forward.

The search doesn't work on the current version even on localhost, so I don't think that setting M_SEARCH_DOWNLOAD_BINARY would make any difference right?

Because of the related issues:
- doxygen/doxygen#6715 Probably not because my doxygen output as of 1.8.14 was free of warnings
- doxygen/doxygen#6714 Maybe

**Comment by mosra** [comment]
> So,1.8.15 triggers the assertions as well but the .html is generated instead on 1.8.14 which doesn't produce any output, although I also added the newline, thanks for the hint.

Um, not sure what you meant here :sweat_smile: I tried locally with current `master` (including the commit that added newline) and it works both on 1.8.15 and 1.8.14. With 1.8.15 it works even with the newline missing, for me at least. They fixed this exact thing (brief docs containing block elements) for 1.8.15, so that makes sense.

So, to be clear: the newline worked for you, and now I just need to handle the assertions more gracefully, right?

> The search doesn't work on the current version even on localhost

![image](https://user-images.githubusercontent.com/344828/50738079-81cbd600-11d0-11e9-9734-9ab6ee014a8b.png)

The `gh-pages` branch was missing the `search.js` file :wink: -- I got confused because I thought the `searchdata.js` is missing, but that one *is* there. Not sure how that happened tho, the script should be copying that unless you disable the search globally. I failed to find the m.css-specific Doxyfile so I was not able to reproduce. Nevertheless, I would suggest enabling the binary search, it's slightly faster to download and process (even though you have just 12 kB of search data, so it is not that big difference).

Also found a few issues regarding parsing `noexcept` specifiers, will fix these (along with the ones reported in #79).

**Comment by Naios** [comment]
Ok, so the previous error I mentioned was due to a non existing favicon and can be ignored.

I managed to get m.css to work again so this behaviour is the same as on your machine now (including the search bar).
So it should be done by making the assertions taking the bad doxygen 1.8.14 output into account,
and allowing larger briefs in sections.

Thanks again for your help and the creation of m.css,
it really helps me to provide a helpful documentation for my project.

**Comment by mosra** [comment]
> due to a non existing favicon

Saw that too, yeah, setting `M_FAVICON =` (empty) in m.css-specific Doxyfile should disable that. There is `favicon-dark.png` bundled with m.css (which also should get copied), but I'm not sure if that one fits your design.

> and allowing larger briefs in sections

No, this was a bug of Doxygen < 1.8.15, the briefs should always be single-paragraph and the rest should go into detailed docs, shown later on the page. Allowing larger briefs would complicate styling *a lot*. I'll update the assertions and to make sure this doesn't happen again I'll try to test with 1.8.13 on the CI as well. Unfortunately not with 1.8.14, since the official binary release was broken and never properly fixed.

> Thanks

Thanks for the appreciation and don't hesitate to open further issues if you see something that doesn't look right ;)

**Comment by mosra** [comment]
So, finally:

- with https://github.com/mosra/m.css/commit/990d4362fc5736e01cca5ea2843517784873a63c and https://github.com/mosra/m.css/commit/540c41fb43745ab91416e866e4938c35f2ced00c the assertion should hopefully not be hit again on 1.8.14 with problematic input (nevertheless, now you already know how to avoid the assertion so all is good)
- and with https://github.com/mosra/m.css/commit/38e0d6230473aa2be8b2f30ff374f52ee4ab5ada the <kbd>noexcept</kbd> labels e.g. [here](https://naios.github.io/continuable/classcti_1_1promise__base.html#adca9714bd11fcbaa4e9c145758feed8b) should be recognized properly

Besides that, since [quite a while ago](https://blog.magnum.graphics/meta/improved-doxygen-documentation-and-search/) the theme supports showing what to `#include` for given class / namespace / symbol (providing you have the files documented using the `@file` command), along with other niceties, so you might want to upgrade :)
