### ISSUE TITLE
MacOS and the Math Plug In

### ISSUE THREAD

**Issue by dscience7** [mosra/m.css#9]
On MacOS, even after installing a LaTeX distribution, the ``latex2svg.py`` utility may not work until you've edited your ``$PATH``. If you have MacTex installed (either via Homebrew or some other means), this solution on [stackexchange](https://tex.stackexchange.com/questions/249966/install-latex-on-mac-os-x-el-capitan-10-11) worked for me.

**Comment by mosra** [comment]
Hi, did you solve the problem in some other way? If not, I think it's worth to mention this in the docs at least, so reopening :)

**Comment by dscience7** [comment]
No I just edited my ``$PATH``.

**Comment by dscience7** [comment]
I will update the docs and submit a pull request

**Comment by mosra** [comment]
Hmm, looking at the suggested solution on stackexchange, I think this could be integrated directly in the `latex2svg.py` utility -- for example it could try a bunch of pre-defined paths (like it's doing already for the Homebrew version of `libgs`) and then modifying the `PATH` on its own.

What do you think? If this could work, I think that's a better solution than telling the users to do it manually.

**Comment by dscience7** [comment]
I'm not sure. The reason the utility doesn't work is because the `latex` command isn't available from the command line. This could be because:

1. The '$PATH` needs updating, or
2. `latex' isn't installed on the system.

Only in the first case should `latex2svg.py` update the `$PATH`. I'm not sure how it would know?

The correct place for the fix would be in the installers for MacTex.

**Comment by mosra** [comment]
> The correct place for the fix would be in the installers for MacTex.

Right, but since the issue was reported more than two years ago and there's no fix for that yet, I doubt they'll do anything about it...

Since people may have MacTex installed only because this math plugin needs it (and they are not using it directly at all), I think `latex2svg.py` should handle it gracefully. I was thinking something like this:

1. if on macOS and the `latex` command is not in `PATH`, check that the usual installation dir exists (which would be `/Library/TeX/Distributions/.DefaultTeX/Contents/Programs/texbin`)
2. if it exists, the user just doesn't have `PATH` updated, so do it and then run the command
3. otherwise, the user doesn't have MacTex installed at all, or it's in some different place, give up

**Comment by dscience7** [comment]
That would be helpful. My only suggestion is the user is made aware their `$PATH` is being changed.

**Comment by mosra** [comment]
Yup -- and reminding that they should do that themselves on a system level, maybe.

If I understand correctly, changing it in the script won't affect the shell session after the script execution ends, right? Or does one need to explicitly push/pop some state?

Unfortunately I don't have any access to macOS environment at the moment, could I ask you to provide a patch? :)

**Comment by dscience7** [comment]
I've never done anything like that before. But I'll have a go.

**Comment by mosra** [comment]
Updated the documentation in b6ab81bcc3f031819edbceabdccd151b38960b5a ([live](http://mcss.mosra.cz/plugins/math-and-code/#math)). I hope that's enough, so closing this.
