### ISSUE TITLE
Doxygen: The output uses `auto` as a return value

### ISSUE THREAD

**Issue by kobalicek** [mosra/m.css#91]
I'm wondering whether it would be possible to not use `auto` as a return value of functions that don't return `auto`: For example a function like this:

   ```uint32_t doSomething(uint32_t x)```

is documented as:

   ```auto doSomething(uint32_t x) -> uint32_t```

To me the `"auto"` and `"->"` text is highly redundant and confusing as the function is not auto, so I would prefer if the output could also respected that. I'm not sure why the information is presented this way, I would guess that it's because "void" and "auto" are relatively small and it makes function names much nicer aligned, however, as I said, it confuses me while browsing the docs.

**Comment by mosra** [comment]
Yes, this is done exactly in order to have the names aligned (and yes, I know, it was a controversial choice). The stock Doxygen theme uses a table to achieve the alignment, but especially with long return types or on narrow screens it was making the output too wide and unreadable and so I ended up doing it this way.

This is, fortunately, only a presentation thing, so you can modify the behavior however you want in your template. The relevant markup is [here](https://github.com/mosra/m.css/blob/4623029a16385634dad1acd31a5be790143ae9a0/doxygen/templates/entry-func.html#L7), see especially the `{% if func.return_type == void %}` part. Even if you don't know Jinja2, it should be pretty easy to modify it to always have the return type before. There are two possibilities how to maintain the modified template:

- either have a fork of this repository with various bits changed (not recommended, as it makes future updates harder due to conflict resolution etc)
- or (recommended) copy the whole contents of the `doxygen/template/` directory somewhere else and point to it using the `--template` parameter of `dox2html5.py`

To make the template overrides easier (so you need to maintain just the modified files, not all of them), I could add some fallbacks to the Jinja2 template search path. Gonna look into how that's done.

**Comment by mosra** [comment]
> To make the template overrides easier (so you need to maintain just the modified files, not all of them), I could add some fallbacks to the Jinja2 template search path. Gonna look into how that's done.

That's done now with 715a682c60a6447745cf9dd1bf014992e6765a6a, so all you need to do in this case is maintaining your own copy of `entry-func.html` and passing its location to `--template` when running `dox2html5.py`. 

Let me know how that works for you.

**Comment by mosra** [comment]
Closing as resolved.
